### PR TITLE
Added video links in lines 153-158.

### PR DESCRIPTION
**Pull request by CBID2**
Here are the videos that I found. Let me know what you think.

### CODE REVIEW

**Comment by CBID2** [comment]
These are some of the videos I found from YouTube channels that do not have an accessibility focus.

**Review by ctoffanin — APPROVED** [review]

**Comment by ctoffanin** [comment]
Thank you so much for contributing!

**Comment by CBID2** [comment]
> Thank you so much for contributing!

Thanks for having me @ctoffanin! I followed your page.

**Review by EmmaDawsonDev — APPROVED** [review]
Thanks for the additions.

**Pull request merged**
